#!/bin/sh

export KUBECONFIG=`pwd`/rke_tools/kube_config_cluster.yml

helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
kubectl create namespace cattle-system

kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.crds.yaml

kubectl create namespace cert-manager
helm repo add jetstack https://charts.jetstack.io
helm repo update

helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v1.0.4
kubectl -n cert-manager rollout status deploy/cert-manager

read -p "Wait for completion"

# Verify cert-manager installation
kubectl get pods --namespace cert-manager

helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname=kube.marms
kubectl -n cattle-system rollout status deploy/rancher
