---

- name: Install initial K3s
  command: >-
    k3sup install
    --cluster
    --host {{ inventory_hostname }}
  delegate_to: localhost
  when: inventory_hostname == master_host

- name: Join K3s
  command: >-
    k3sup join
    --server
    --host {{ inventory_hostname }}
    --server-host {{ master_host }}
  delegate_to: localhost
  when: inventory_hostname != master_host