---

- name: Download helm binary
  get_url:
    url: https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz
    checksum: sha256:https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz.sha256sum
    dest: /tmp/helm-{{ helm_version }}.tar.gz
    owner: root
    group: root
    mode: 0755

- name: Create temp helm folder
  ansible.builtin.file:
    path: /tmp/helm-{{ helm_version }}
    state: directory

- name: Extract helm binary
  ansible.builtin.unarchive:
    src: /tmp/helm-{{ helm_version }}.tar.gz
    dest: /tmp/helm-{{ helm_version }}
    remote_src: yes

- name: Install helm binary
  ansible.builtin.copy:
    src: /tmp/helm-{{ helm_version }}/linux-amd64/helm
    dest: /usr/local/bin/helm
    remote_src: yes
    owner: root
    group: root
    mode: 0755

- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: stable-legacy
    repo_url: "https://charts.helm.sh/stable"

- name: Add Prometheus chart repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Deploy latest version of Prometheus chart inside monitoring namespace
  kubernetes.core.helm:
    name: stable
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    create_namespace: true
    values:
      alertmanager:
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - alertmanager.service.marms
      server:
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - monitoring.service.marms