---

- name: Install package requirements
  apt:
    name:
      - python3-pip
  when: ansible_distribution in ['Ubuntu', 'Debian']

- name: Install package requirements
  dnf:
    name:
      - python3-pip
    state: latest
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']

- name: Install python requirements
  pip:
    name:
      - kubernetes

- name: Download helm binary
  get_url:
    url: https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz
    checksum: sha256:https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz.sha256sum
    dest: /tmp/helm-{{ helm_version }}.tar.gz
    owner: root
    group: root
    mode: 0755

- name: Create temp helm folder
  ansible.builtin.file:
    path: /tmp/helm-{{ helm_version }}
    state: directory

- name: Extract helm binary
  ansible.builtin.unarchive:
    src: /tmp/helm-{{ helm_version }}.tar.gz
    dest: /tmp/helm-{{ helm_version }}
    remote_src: yes

- name: Install helm binary
  ansible.builtin.copy:
    src: /tmp/helm-{{ helm_version }}/linux-amd64/helm
    dest: /usr/local/bin/helm
    remote_src: yes
    owner: root
    group: root
    mode: 0755

- name: Install kubernetes resources
  include_tasks: "{{ item }}"
  with_items:
    - kubernetes/charts.yaml
    - kubernetes/blocky.yaml
    - kubernetes/openebs.yaml
    - kubernetes/cert-manager.yaml
    - kubernetes/rancher.yaml
