apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard-home
  namespace: argocd
spec:
  destination:
    namespace: adguard-home
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: 'https://k8s-at-home.com/charts/'
    targetRevision: 5.0.1
    chart: adguard-home
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: adguard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true