apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  destination:
    namespace: rook-ceph
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: 'https://charts.rook.io/release'
    targetRevision: v1.7.8
    chart: rook-ceph
    server: 'https://kubernetes.default.svc'
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-cluster
  namespace: argocd
spec:
  destination:
    namespace: rook-ceph-cluster
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoUrl: 'https://charts.rook.io.release'
    targetRevision: v1.7.8
    chart: rook-ceph-cluster
    server: 'https://kubernetes.default.svc'
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

