- name: Regular maintenance
  hosts: all
  tasks:
  - name: Install common packages
    apt:
      name:
      - cockpit
      - cockpit-pcp
      - open-iscsi
      - docker.io
  - name: Upgrade the OS (apt-get dist-upgrade)
    apt:
      upgrade: dist
      autoremove: yes

- name: Gluster setup
  hosts: all
  tasks:
  - name: Install gluster
    apt:
      name:
      - glusterfs-server
      - glusterfs-client
  - name: Enable glusterd
    ansible.builtin.systemd:
      name: glusterd
      state: started
      enabled: yes

  - name: Create a trusted storage pool
    gluster.gluster.gluster_peer:
      state: present
      nodes: {{ all }}

  - name: create gluster volume
    gluster.gluster.gluster_volume:
      state: present
      name: gv0
      bricks: /data/disk1/gv0
      rebalance: yes
      replicas: 1
      cluster:
        - cluster1.marms
    run_once: true

  - name: start gluster volume
    gluster.gluster.gluster_volume:
      state: started
      name: gv0
    run_once: true

  - name: mount gluster volume
    ansible.posix.mount:
      path: /mnt/gluster/gv0
      src: /gv0
      fstype: glusterfs
      state: mounted

- name: K3s
  import_playbook: ../external/k3s-ansible/site.yml

- hosts: master[0]
  roles:
    - role: kubectl_installer
