- hosts: all
  tasks:
  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: charlie
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"