- name: Deploy cert-manager
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: cert-manager
    chart_ref: cert-manager/cert-manager
    chart_version: v1.5.1
    release_namespace: cert-manager
    create_namespace: true
    wait: true
    values:
      installCRDs: true
