- name: Add K8s at home chart repo
  kubernetes.core.helm_repository:
    name: k8s-at-home
    repo_url: "https://k8s-at-home.com/charts/"

- name: Add cert-manager chart repo
  kubernetes.core.helm_repository:
    name: cert-manager
    repo_url: "https://charts.jetstack.io"

- name: Add OpenEBS chart repo
  kubernetes.core.helm_repository:
    name: openebs
    repo_url: "https://openebs.github.io/charts"

- name: Add Rancher chart repo
  kubernetes.core.helm_repository:
    name: rancher-stable
    repo_url: "https://releases.rancher.com/server-charts/stable"

- name: Add WikiJs chart repo
  kubernetes.core.helm_repository:
    name: requarks
    repo_url: "https://charts.js.wiki"