- name: NFS Server endpoint
  kubernetes.core.k8s:
    state: present
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: nfs-server
        labels:
          app: nfs-server
      spec:
        type: ClusterIP  # use "LoadBalancer" to get a public ip
        selector:
          app: nfs-server
        ports:
          - name: tcp-2049
            port: 2049
            protocol: TCP
          - name: udp-111
            port: 111
            protocol: UDP

- name: NFS Server deployment
  kubernetes.core.k8s:
    state: present
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: nfs-server
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: nfs-server
        template:
          metadata:
            name: nfs-server
            labels:
              app: nfs-server
          spec:
            nodeSelector:
              "kubernetes.io/os": linux
            containers:
              - name: nfs-server
                image: itsthenetwork/nfs-server-alpine:latest
                env:
                  - name: SHARED_DIRECTORY
                    value: "/gv0"
                volumeMounts:
                  - mountPath: /gv0
                    name: nfs-vol
                securityContext:
                  privileged: true
                ports:
                  - name: tcp-2049
                    containerPort: 2049
                    protocol: TCP
                  - name: udp-111
                    containerPort: 111
                    protocol: UDP
            volumes:
              - name: nfs-vol
                hostPath:
                  path: /mnt/gluster/gv0
                  type: DirectoryOrCreate

- name: Deploy CSI-Driver-NFS
  kubernetes.core.helm:
    name: csi-driver-nfs
    chart_ref:  csi-driver-nfs/csi-driver-nfs
    release_namespace: kube-system
    create_namespace: true
    wait: true
    values:
      controller:
        runOnMaster: true
        replicas: 1
      feature:
        enableFSGroupPolicy: true

- name: NFS StorageClass
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: nfs-csi
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: nfs.csi.k8s.io
      parameters:
        server: nfs-server.default.svc.cluster.local
        share: /gv0
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      mountOptions:
        - hard
        - nfsvers=4.1