- name: NFS namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: nfs

- name: NFS Server endpoint
  kubernetes.core.k8s:
    state: present
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: nfs-server
        namespace: nfs
        labels:
          app: nfs-server
      spec:
        type: ClusterIP  # use "LoadBalancer" to get a public ip
        selector:
          app: nfs-server
        ports:
          - name: tcp-2049
            port: 2049
            protocol: TCP
          - name: udp-111
            port: 111
            protocol: UDP

- name: NFS Server deployment
  kubernetes.core.k8s:
    state: present
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: nfs-server
        namespace: nfs
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: nfs-server
        template:
          metadata:
            name: nfs-server
            labels:
              app: nfs-server
          spec:
            nodeSelector:
              "kubernetes.io/os": linux
            containers:
              - name: nfs-server
                image: itsthenetwork/nfs-server-alpine:latest
                env:
                  - name: SHARED_DIRECTORY
                    value: "/gv0"
                volumeMounts:
                  - mountPath: /exports
                    name: nfs-vol
                securityContext:
                  privileged: true
                ports:
                  - name: tcp-2049
                    containerPort: 2049
                    protocol: TCP
                  - name: udp-111
                    containerPort: 111
                    protocol: UDP
            volumes:
              - name: nfs-vol
                hostPath:
                  path: /mnt/gluster/gv0
                  type: DirectoryOrCreate

- name: Deploy nfs-subdir-external-provisioner
  kubernetes.core.helm:
    name: nfs-subdir-external-provisioner
    chart_ref:  nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    release_namespace: kube-system
    create_namespace: true
    wait: true
    values:
      nfs:
        server: nfs-server.default.svc.cluster.local
        path: /gv0
