- name: Deploy Rancher
  kubernetes.core.helm:
    name: rancher
    chart_ref:  rancher-stable/rancher
    release_namespace: cattle-system
    create_namespace: true
    wait: true
    values:
      hostname: rancher.service.marms
      ingress:
        tls:
          source: rancher