- name: Deploy Rancher
  kubernetes.core.helm:
    name: rancher
    chart_ref:  rancher-stable/rancher
    release_namespace: cattle-system
    create_namespace: true
    wait: true
    values:
      hostname: rancher.service.marms
      ingress:
        tls:
          source: rancher

- name: Remove Rancher default storage class
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: local-path
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"