- name: Deploy Rook Ceph Operator
  kubernetes.core.helm:
    name: rook-ceph
    chart_ref: rook-release/rook-ceph
    release_namespace: rook-ceph
    create_namespace: true
    wait: true

- name: Deploy Rook Ceph Cluster
  kubernetes.core.helm:
    name: rook-ceph-cluster
    chart_ref: rook-release/rook-ceph-cluster
    release_namespace: rook-ceph
    create_namespace: true
    wait: true
    values:
      dashboard:
        enabled: true
        ssl: false