- name: whoami namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: whoami

- name: whoami deployment
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: whoami
        namespace: whoami
      spec:
        selector:
          matchLabels:
            app: whoami
        replicas: 1
        template:
          metadata:
            labels:
              app: whoami
          spec:
            containers:
              - name: whoami
                image: containous/whoami:v1.5.0
                ports:
                  - containerPort: 80

- name: whoami service
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: whoami
        namespace: whoami
      spec:
        type: ClusterIP
        ports:
          - port: 5678
            targetPort: 80
        selector:
          app: whoami

- name: whoami ingress
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    wait: true
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: whoami
        namespace: whoami
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/auth-url: "https://authentikprox.{{ domain }}/akprox/auth/nginx"
          nginx.ingress.kubernetes.io/auth-signin: "https://authentikprox.{{ domain }}/akprox/start?rd=$escaped_request_uri"
          nginx.ingress.kubernetes.io/auth-response-headers: "Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid"
          nginx.ingress.kubernetes.io/auth-snippet: "proxy_set_header Host $http_host;"
      spec:
        rules:
          - host: whoami.{{ domain }}
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: whoami
                      port:
                        number: 5678
        tls:
          - secretName: whoami-tls
            hosts:
              - whoami.{{ domain }}

- name: Wait for whoami certificate
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    kind: Secret
    wait: yes
    name: whoami-tls
    namespace: whoami